# Generated by Django 4.0.1 on 2022-04-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('userinfo', models.TextField()),
                ('stuid', models.TextField()),
                ('tele', models.TextField()),
                ('email', models.TextField()),
            ],
            options={
                'db_table': 'AdminUsers',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsID', models.IntegerField()),
                ('title', models.TextField()),
                ('web_site', models.TextField()),
                ('image_src', models.TextField()),
                ('text', models.TextField()),
                ('source', models.TextField()),
                ('show_time', models.TextField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('userinfo', models.TextField()),
                ('tele', models.TextField()),
                ('email', models.TextField()),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
